fragment NewsTalkRoomParts on NewsTalkRoom {
  id
  allMessageSeen
  members {
    edges {
      node {
        id
        user {
          ...UserParts
        }
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
  news {
    ...NewsTalkRoomParentParts
  }
  messages(first: 20) {
    edges {
      node {
        ...NewsTalkRoomMessageParts
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
