fragment OneOnOneTalkRoomMessageParts on OneOnOneTalkRoomMessage {
  id
  text
  createdAt
  sender {
    id
    name
    imageUrl
  }
  roomId
  replyMessage {
    id
    text
    createdAt
    sender {
      id
      name
      imageUrl
    }
  }
}
