fragment OneOnOneTalkRoomParts on OneOnOneTalkRoom {
  id
  allMessageSeen
  updatedAt
  sender {
    ...UserParts
  }
  recipient {
    ...UserParts
  }
  messages(first: 20) {
    edges {
      node {
        ...OneOnOneTalkRoomMessageParts
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
