fragment ThoughtTalkRoomsParts on ThoughtTalkRoom {
  id
  createdAt
  allMessageSeen
  members {
    id
    user {
      ...UserParts
    }
  }
  thought {
    id
    title
    text
  }
  messages {
    id
    text
    createdAt
    sender {
      ...UserParts
    }
    roomId
  }
}
