fragment ThoughtTalkRoomParts on ThoughtTalkRoom {
  id
  createdAt
  allMessageSeen
  members {
    edges {
      node {
        id
        user {
          id
          name
          imageUrl
        }
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
  thought {
    id
    title
    text
  }
  messages(first: 20) {
    edges {
      node {
        ...ThoughtTalkRoomMessageParts
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
