fragment ThoughtTalkRoomParts on ThoughtTalkRoom {
  id
  createdAt
  allMessageSeen
  members {
    edges {
      node {
        id
        user {
          ...UserParts
        }
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
  thought {
    ...ThoughtTalkRoomParentParts
  }
  messages(first: 20) {
    edges {
      node {
        ...ThoughtTalkRoomMessageParts
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
