query Follows($cursor: String, $q: String) {
  follows(first: 30, after: $cursor, q: $q) {
    edges {
      node {
        ...UserParts
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
