query GetActiveData {
  thoughtTalkRooms: thoughtTalkRooms {
    ...ThoughtTalkRoomParts
  }
  newsTalkRooms: newsTalkRooms {
    ...NewsTalkRoomParts
  }
  oneOnOneTalkRooms: oneOnOneTalkRooms {
    ...OneOnOneTalkRoomParts
  }
}
