query GetActiveData {
  thoughtTalkRooms {
    ...ThoughtTalkRoomParts
  }
  newsTalkRooms {
    ...NewsTalkRoomParts
  }
  oneOnOneTalkRooms {
    ...OneOnOneTalkRoomParts
  }
  notifications {
    edges {
      node {
        id
        createdAt
        type
        talkRoomType
        talkRoomId
        seen
        performer {
          id
          name
          imageUrl
        }
        thought {
          id
        }
      }
      cursor
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
