query GetLikedThoughts($after: String, $userId: ID!) {
  user(id: $userId) {
    id
    likedThoughts(after: $after) {
      edges {
        node {
          id
          thought {
            ...ThoughtParts
          }
        }
        cursor
      }
      pageInfo {
        ...PageInfoParts
      }
    }
  }
}
