query GetLikedThoughts($after: String, $userId: ID!) {
  userResult(id: $userId) {
    ... on User {
      id
      likedThoughts(after: $after) {
        edges {
          node {
            id
            thought {
              ...ThoughtParts
            }
          }
          cursor
        }
        pageInfo {
          ...PageInfoParts
        }
      }
    }
    ... on Deleted {
      message
    }
  }
}
