query GetNewsTalkRoomMessages($talkRoomId: Int!, $messageCursor: String) {
  newsTalkRoom(id: $talkRoomId) {
    messages(first: 20, after: $messageCursor) {
      edges {
        node {
          ...NewsTalkRoomMessageParts
        }
        cursor
      }
      pageInfo {
        ...PageInfoParts
      }
    }
  }
}
