query GetPickedNews($cursor: String, $userId: ID!) {
  user(id: $userId) {
    id
    pickedNews(first: 20, after: $cursor) {
      edges {
        node {
          id
          news {
            ...NewsParts
            picked
          }
        }
        cursor
      }
      pageInfo {
        ...PageInfoParts
      }
    }
  }
}
