query GetPickedNews($cursor: String, $userId: ID!) {
  userResult(id: $userId) {
    ... on User {
      id
      pickedNews(first: 20, after: $cursor) {
        edges {
          node {
            id
            news {
              ...NewsParts
              picked
            }
          }
          cursor
        }
        pageInfo {
          ...PageInfoParts
        }
      }
    }
    ... on Deleted {
      message
    }
  }
}
