query GetThoughtTalkRoom($id: ID!) {
  thoughtTalkRoom(id: $id) {
    id
    createdAt
    members {
      id
      user {
        id
        name
        imageUrl
      }
    }
    thought {
      id
    }
    messages {
      id
      text
      createdAt
      sender {
        id
        name
        imageUrl
      }
    }
  }
}
