query GetThoughtTalkRooms {
  thoughtTalkRooms {
    id
    createdAt
    members {
      id
      user {
        id
        name
        imageUrl
      }
    }
    thought {
      id
      title
      text
    }
    messages {
      id
      text
      createdAt
      sender {
        id
        name
        imageUrl
      }
      roomId
    }
  }
}
