query GetThoughtTalkRoomMessages($id: Int!, $messageCursor: String) {
  thoughtTalkRoom(id: $id) {
    id
    messages(first: 20, after: $messageCursor) {
      edges {
        node {
          ...ThoughtTalkRoomMessageParts
        }
        cursor
      }
      pageInfo {
        ...PageInfoParts
      }
    }
  }
}
