query InitialData {
  me: me {
    id
    name
    bio
    imageUrl
    facebook
    twitter
    instagram
    linkedin
    loggedIn
    receiveOneOnOneTalkRoomMessage
  }
  thoughtTalkRooms: thoughtTalkRooms {
    ...ThoughtTalkRoomParts
  }
  newsTalkRooms: newsTalkRooms {
    ...NewsTalkRoomParts
  }
  oneOnONeTalkRooms: oneOnOneTalkRooms {
    ...OneOnOneTalkRoomParts
  }
}
