query News($genre: NewsGenre!, $cursor: String) {
  news(genre: $genre, first: 30, after: $cursor) {
    edges {
      node {
        id
        title
        link
        image
        articleCreatedAt
        genre
        provider
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
