query Thoughts($genre: Genre!, $cursor: String) {
  thoughts(genre: $genre, first: 20, after: $cursor) {
    edges {
      node {
        id
        title
        text
        createdAt
        contributor {
          id
          name
          imageUrl
        }
        picked
        images {
          id
          url
          width
          height
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
