query Thoughts($genre: Genre!) {
  thoughts(genre: $genre) {
    edges {
      node {
        id
        title
        text
        createdAt
        contributor {
          id
          name
          imageUrl
        }
        picked {
          id
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
