subscription OnThoughtTalkRoomMessageCreated($roomIds: [Int]!) {
  thoughtTalkRoomMessageCreated(roomIds: $roomIds) {
    id
    text
    createdAt
    sender {
      ...UserParts
    }
    roomId
  }
}
