subscription OnThoughtTalkRoomMessageCreated($roomIds: [Int]!, $userId: ID!) {
  thoughtTalkRoomMessageCreated(roomIds: $roomIds, userId: $userId) {
    id
    text
    createdAt
    sender {
      ...UserParts
    }
    roomId
  }
}
