subscription OnThoughtTalkRoomMessageCreated {
  thoughtTalkRoomMessageCreated {
    id
    text
    createdAt
    sender {
      # id
      # name
      # imageUrl
      ...UserParts
    }
    roomId
  }
}
